### PR TITLE
Create Break_a_palindrome.java

### PR DESCRIPTION
**Pull request by Sujatha369**
This is a leetcode medium level problem. This java code changes one character in the input palindrome such that it is the lexicographically smallest non palindromic string possible. If not it returns null.

### CODE REVIEW

**Comment by Sujatha369** [comment]
@vedanshi555 Please consider it under Hacktoberfest 2022

**Comment by vedanshiprajapati** [comment]
hey, can you also mention the question number in the title?

**Review by Sujatha369 — COMMENTED** [review]
Just added the question number in the title.

**Review by vedanshiprajapati — APPROVED** [review]
great! thanks for contributing!

**Pull request merged**
